name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-Cronometer'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

#    - name: Test
#      run: ./gradlew test
#      env:
#        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

    - name: Publish
      run: ./gradlew build -x test publish --no-parallel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
